use_frameworks!
platform :ios, '12.0'

target 'QuickTodo' do
  # core RxSwift
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'

  # Community projects
  pod 'Action'
  
  # Network
  pod 'Alamofire'
  pod 'RxAlamofire'
  
  # Realm database
  pod 'RealmSwift'
  pod 'RxRealm'
  
  #other
#  pod 'Reachability'

#  target 'QuickTodoTests' do
#    pod 'RxTest'
#    pod 'RxBlocking'
#    pod 'OHHttpStubs'
#    pod 'OHttpStubs/Swift'
#    pod 'Nimble'
#    pod "RxNimble'
#  end

end
