platform :ios, '12.0'

use_frameworks!

target 'QuickTodo' do
  # core RxSwift
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'

  # Community projects
  pod 'Action'
  
  # Alamofire
#  pod 'Alamfire'
#  pod 'RxAlamofire'
#  pod "SwiftyJSON"

#  pod 'Moya'???
#  pod 'RxMoya'???
#  pod 'ObjectMapper'???


  # Realm database
  pod 'RealmSwift'
  pod 'RxRealm'
  
#  target 'QuickTodoTests' do
#    pod 'RxTest'
#    pod 'RxBlocking'
#  end

end
